/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KhachHangGUI1 extends javax.swing.JDialog {

    DefaultTableModel model=new DefaultTableModel();
    KhachHangBUS bus=new KhachHangBUS();
    public KhachHangGUI1(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        model=(DefaultTableModel) tb1.getModel();
        this.setLocationRelativeTo(null);
         showdl();
    }

    public void showdl(){
        for(KhachHangDTO kh: bus.readdskh()){
            model.addRow(new Object[] {
            kh.getMa(),kh.getHo(),kh.getTen(),kh.getNgaysinh(),kh.getGender(),kh.getDiachi(),kh.getSdt()
            });
        }
       tb1.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lbMaKH = new javax.swing.JLabel();
        txMaKH = new javax.swing.JTextField();
        lbHo = new javax.swing.JLabel();
        txHo = new javax.swing.JTextField();
        lbTen = new javax.swing.JLabel();
        txTen = new javax.swing.JTextField();
        raNam = new javax.swing.JRadioButton();
        raNu = new javax.swing.JRadioButton();
        ldDate = new javax.swing.JLabel();
        lbSdt = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        txSdt = new javax.swing.JTextField();
        txDiaChi = new javax.swing.JTextField();
        txDate = new com.toedter.calendar.JDateChooser();
        p3 = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox<>();
        lbInfo = new javax.swing.JLabel();
        txInfo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khách hàng");

        p1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        lbMaKH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMaKH.setText("Mã khách hàng:");

        lbHo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbHo.setText("Họ :");

        lbTen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTen.setText("Tên :");

        raNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(raNam);
        raNam.setText("Nam");

        raNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(raNu);
        raNu.setText("Nữ");

        ldDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ldDate.setText("Ngày sinh :");

        lbSdt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSdt.setText("Số diện thoại : ");

        lbDiaChi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDiaChi.setText("Địa chỉ :");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbMaKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(raNu))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbHo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ldDate)
                .addGap(18, 18, 18)
                .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSdt)
                    .addComponent(lbDiaChi))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDiaChi)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(txSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaKH)
                    .addComponent(txMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raNam)
                    .addComponent(raNu)
                    .addComponent(lbSdt)
                    .addComponent(txSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbHo)
                        .addComponent(txHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTen)
                        .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ldDate))
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDiaChi)
                        .addComponent(txDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        lbSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSearch.setText("Tìm kiếm theo :");

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã ", "Tên", "Họ" }));

        lbInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbInfo.setText("Nhập thông tin :");

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-more-25.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(lbSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(lbInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearch)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInfo)
                    .addComponent(btnSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-insert-row-25.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-25.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-row-25.png"))); // NOI18N
        btnXoa.setText("Xóa");

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eye-checked-25.png"))); // NOI18N
        btnShow.setText("Hiển thị");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reset-25.png"))); // NOI18N
        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit-25.png"))); // NOI18N
        btnThoat.setText("Quay lại");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ khách hàng", "Tên khách hàng", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnThem))
                        .addGap(47, 47, 47)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShow)
                            .addComponent(btnReset)
                            .addComponent(btnThoat))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(check()){
            
        KhachHangDTO kh1=textfield();
        
       int i=tb1.getSelectedRow();
       if(i>=0){
         int res=JOptionPane.showConfirmDialog(rootPane, "Bạn muốn sửa khách hàng này?");
         if(res==JOptionPane.YES_OPTION){
             if(bus.changekh(kh1)){
                 KhachHangDTO kh=bus.readdskh().set(i, kh1);
                 model.setValueAt(kh1.getMa(),i,0);
                 model.setValueAt(kh1.getHo(),i,1);
                 model.setValueAt(kh1.getTen(),i,2);
                 model.setValueAt(kh1.getNgaysinh(),i,3);
                 model.setValueAt(kh1.getGender(),i,4);
                 model.setValueAt(kh1.getDiachi(),i,5);
                 model.setValueAt(kh1.getSdt(),i,6);
                 reset();
                 JOptionPane.showMessageDialog(rootPane,"Sửa thành công");
             }
             else
                 JOptionPane.showMessageDialog(rootPane,"Sửa thất bại");
           }
         
        }else
           JOptionPane.showMessageDialog(rootPane,"Sửa Thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       KhachHangDTO kh=new KhachHangDTO();
       boolean ischeck6=true;
       kh.setMa(txMaKH.getText());
       kh.setHo(txHo.getText());
       kh.setTen(txTen.getText());
       try {
            kh.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").format(txDate.getDate()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Bạn chưa chọn ngày");
            ischeck6=false;
        }
       if(raNam.isSelected()){
           kh.setGender("Nam");
       }
       else{
        kh.setGender("Nữ");
    }
      kh.setDiachi(txDiaChi.getText());
      kh.setSdt(txSdt.getText());
        
      
     if(ischeck6)
     {  
         String ma=txMaKH.getText();
         int i=bus.kiemtratrung(ma);
     if(i==1&&bus.addkh(kh)){
         check();
         bus.dskh.add(kh);
         setrow(kh);
         reset();
         JOptionPane.showMessageDialog(rootPane,"Thêm thành công");
     }
     else{
         JOptionPane.showMessageDialog(rootPane,"Trùng Mã khách hàng");
     }
     }
     else{
         JOptionPane.showMessageDialog(rootPane,"Thêm thất bại");
     }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
      model.setRowCount(0);
        showdl();
        reset();        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int i= tb1.getSelectedRow();
        if(i>=0){
        txMaKH.setText(tb1.getModel().getValueAt(i, 0).toString());
        txHo.setText(tb1.getModel().getValueAt(i, 1).toString());
        txTen.setText(tb1.getModel().getValueAt(i, 2).toString());
        
            try {
                txDate.setDate( new SimpleDateFormat("yyyy-MM-dd").parse(tb1.getModel().getValueAt(i,3)+""));
              
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        if(tb1.getModel().getValueAt(i,4).equals("Nam")){
            raNam.setSelected(true);
        }    
       if(tb1.getModel().getValueAt(i,4).equals("Nữ")){
            raNu.setSelected(true);
        }  
        txDiaChi.setText(tb1.getModel().getValueAt(i, 5).toString());
        txSdt.setText(tb1.getModel().getValueAt(i, 6).toString());
       txMaKH.setEnabled(false);
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txMaKH.setText("");
        txHo.setText("");
        txTen.setText("");
        txDate.setDate(null);
        raNam.setSelected(true);
        txDiaChi.setText("");
        txSdt.setText("");
       txMaKH.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    public void header(){
        Vector header=new Vector();
        header.add("Mssv");
        header.add("Ho");
        header.add("Ten");
        header.add("Diachi");
        header.add("Email");
        header.add("Sdt");
        header.add("Diem");
       model=new DefaultTableModel(header,0);
       
    }
    public void showSearchMa(){
        model.setRowCount(0);
        for(KhachHangDTO kh: bus.timKiemID(txInfo.getText().toLowerCase())){
            model.addRow(new Object[]{
             kh.getMa(),kh.getHo(),kh.getTen(),kh.getNgaysinh(),kh.getGender(),kh.getDiachi(),kh.getSdt()  
           });
        }
    }
    public void showSearchTen(){
        
        model.setRowCount(0);
        for(KhachHangDTO kh: bus.timKiemten(txInfo.getText())){
            model.addRow(new Object[]{
             kh.getMa(),kh.getHo(),kh.getTen(),kh.getNgaysinh(),kh.getGender(),kh.getDiachi(),kh.getSdt()      
           });
        }
    }
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(cbSearch.getSelectedIndex()==0){
            showSearchMa();
        }
         if(cbSearch.getSelectedIndex()==1){
            showSearchTen();
        }
         
        
    }//GEN-LAST:event_btnSearchActionPerformed

    public KhachHangDTO textfield(){
        KhachHangDTO kh= new KhachHangDTO();
         kh.setMa(txMaKH.getText());
         kh.setHo(txHo.getText());
         kh.setTen(txTen.getText());
         kh.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").format(txDate.getDate()));
         if(raNam.isSelected()){
             kh.setGender("Nam");
         }
         if(raNu.isSelected()){
             kh.setGender("Nữ");
         }
         kh.setDiachi(txDiaChi.getText());
         kh.setSdt(txSdt.getText());
         return kh;
    }
    public void reset(){
        txMaKH.setText("");
        txHo.setText("");
        txTen.setText("");
        txDate.setDate(null);
        raNam.setSelected(true);
        txDiaChi.setText("");
        txSdt.setText("");
       txMaKH.setEnabled(true);
        
    }
    public void setrow(KhachHangDTO kh){
        Vector row=new Vector();
        row.add(kh.getMa());
        row.add(kh.getHo());
        row.add(kh.getTen());
        row.add(kh.getNgaysinh());
        row.add(kh.getGender());
        row.add(kh.getDiachi());
        row.add(kh.getSdt());
        model.addRow(row);
        tb1.setModel(model);
    }
    public boolean check(){
        KhachHangDTO kh=new KhachHangDTO();
        boolean ischeck1=true;
        if(txMaKH.getText().length()==0){
        JOptionPane.showMessageDialog(rootPane,"Bạn chưa nhập Mã Khách Hàng");
        ischeck1=false;
      }  
      
      if(txHo.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn chưa nhập họ!!");
          ischeck1=false;
          
      }
      if(txTen.getText().length()==0){
         JOptionPane.showMessageDialog(rootPane,"Bạn chưa nhập tên"); 
          ischeck1=false;
          
      }
      if(txDiaChi.getText().length()==0){
         JOptionPane.showMessageDialog(rootPane,"Bạn chưa nhập địa chỉ"); 
         ischeck1=false;
         
      }
     
      if(txSdt.getText().length()>10){
         JOptionPane.showMessageDialog(rootPane,"SĐT không vượt quá 10 số");
          ischeck1=false;
          
      }
      if(txSdt.getText().length()==0){
          JOptionPane.showMessageDialog(rootPane,"Bạn chưa nhập SĐT");
          ischeck1=false;
      }
      return ischeck1;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhachHangGUI dialog = new KhachHangGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbMaKH;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel ldDate;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JRadioButton raNam;
    private javax.swing.JRadioButton raNu;
    private javax.swing.JTable tb1;
    private com.toedter.calendar.JDateChooser txDate;
    private javax.swing.JTextField txDiaChi;
    private javax.swing.JTextField txHo;
    private javax.swing.JTextField txInfo;
    private javax.swing.JTextField txMaKH;
    private javax.swing.JTextField txSdt;
    private javax.swing.JTextField txTen;
    // End of variables declaration//GEN-END:variables
}
