/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.SanPhamBUS;
import DTO.SanPhamDTO;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SanPhamGUI extends javax.swing.JDialog {
    DefaultTableModel mode = new DefaultTableModel();
    SanPhamBUS bus= new SanPhamBUS();
    /**
     * Creates new form SanPhamGUI
     */
    public SanPhamGUI(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        mode= (DefaultTableModel) tbl.getModel();
        this.setLocationRelativeTo(null);
        Docdulieu();
        loadComboBox();
        
        
    }
    
   public void Docdulieu(){
       for(SanPhamDTO sp :bus.docdulieu()){
           mode.addRow(new Object[]{
               sp.getMaSP(),sp.getTenSP(),sp.getGiaGoc(),sp.getDonGia(),sp.getSoLuong(),sp.getDonViTinh(),sp.getMaLoai()
           });
       }
       tbl.setModel(mode);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbMaLoai = new javax.swing.JComboBox<>();
        lbTen = new javax.swing.JLabel();
        txTen = new javax.swing.JTextField();
        lbGiaGoc = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        txGiaGoc = new javax.swing.JTextField();
        txDonGia = new javax.swing.JTextField();
        lbSL = new javax.swing.JLabel();
        lbDVT = new javax.swing.JLabel();
        cbDVT = new javax.swing.JComboBox<>();
        txSL = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        lbTimKiem = new javax.swing.JLabel();
        cbTimKiem = new javax.swing.JComboBox<>();
        lbThongtin = new javax.swing.JLabel();
        txThongtin = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sản phẩm");

        p1.setBackground(new java.awt.Color(255, 255, 255));

        lbTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("QUẢN LÝ SẢN PHẨM");

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        lbID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbID.setText("Mã sản phẩm :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mã loại :");

        cbMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbTen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTen.setText("Tên sản phẩm :");

        lbGiaGoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaGoc.setText("Giá gốc :");

        lbDonGia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDonGia.setText("Đơn giá :");

        lbSL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSL.setText("Số lượng :");

        lbDVT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDVT.setText("Đơn vị tính :");

        cbDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cây", "hộp", "gói", "cái", "trái", "ly" }));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTen))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbID)
                        .addGap(18, 18, 18)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbGiaGoc)
                        .addGap(18, 18, 18)
                        .addComponent(txGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(lbDonGia)
                        .addGap(18, 18, 18)
                        .addComponent(txDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDVT)
                    .addComponent(lbSL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGiaGoc)
                    .addComponent(txGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSL)
                    .addComponent(txSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTen)
                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDonGia)
                    .addComponent(txDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDVT)
                    .addComponent(cbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-insert-row-25.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-25.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit-25.png"))); // NOI18N
        btnExit.setText("Quay lại");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eye-checked-25.png"))); // NOI18N
        btnShow.setText("Hiển thị");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reset-25.png"))); // NOI18N
        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        lbTimKiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTimKiem.setText("Tìm kiếm theo :");

        cbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sản phẩm", "Tên sản phẩm" }));
        cbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTimKiemActionPerformed(evt);
            }
        });

        lbThongtin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbThongtin.setText("Nhập thông tin :");

        txThongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txThongtinActionPerformed(evt);
            }
        });
        txThongtin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txThongtinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txThongtinKeyReleased(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-more-25.png"))); // NOI18N
        btnTim.setText("Tìm kiếm ");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(lbTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(lbThongtin)
                        .addGap(18, 18, 18)
                        .addComponent(txThongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTimKiem)
                    .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThongtin)
                    .addComponent(txThongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(6, 6, 6))
        );

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá gốc", "Đơn giá", "Số lượng", "Đơn vị tính", "Mã loại"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitle)
                .addGap(16, 16, 16)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int i= tbl.getSelectedRow();
        if(i>=0){
        txID.setText(tbl.getModel().getValueAt(i, 0).toString());
        txTen.setText(tbl.getModel().getValueAt(i, 1).toString());
        txGiaGoc.setText(tbl.getModel().getValueAt(i, 2).toString());
        txDonGia.setText(tbl.getModel().getValueAt(i, 3).toString());
        txSL.setText(tbl.getModel().getValueAt(i, 4).toString());
        cbDVT.setSelectedItem(tbl.getModel().getValueAt(i, 5).toString());
        cbMaLoai.setSelectedItem(tbl.getModel().getValueAt(i, 6).toString());
        txID.setEnabled(false);
        cbMaLoai.setEnabled(false);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        mode.setRowCount(0);
        Docdulieu();
        reset();
    }//GEN-LAST:event_btnShowActionPerformed

     
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        SanPhamDTO sp= new SanPhamDTO();
        int flag=1,flag2=1,flag3=1,flag4=1;
        if(kt()){
        sp.setMaSP(txID.getText());
        sp.setTenSP(txTen.getText());
            try {
                 sp.setGiaGoc(Float.parseFloat(txGiaGoc.getText()));
                 flag=1;
            } catch (Exception e) {
                flag=0;
                JOptionPane.showMessageDialog(rootPane, "Gía gốc phải là số");
               
            }
            try {
                sp.setDonGia(Float.parseFloat(txDonGia.getText()));
                 flag2=1;
            } catch (Exception e) {
                flag2=0;
                JOptionPane.showMessageDialog(rootPane, "Đơn giá phải là số");
            }
            try {
                 sp.setSoLuong(Integer.parseInt(txSL.getText()));
                 flag3=1;
            } catch (Exception e) {
                flag3=0;
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
            }
        sp.setMaLoai((String)cbMaLoai.getSelectedItem());
        sp.setDonViTinh((String) cbDVT.getSelectedItem());
        for(int i=0;i<bus.dssp.size();i++){
            if(bus.dssp.get(i).getMaSP().trim().equals(txID.getText().trim())){
                flag4=0;
                JOptionPane.showMessageDialog(rootPane, "Trùng mã sản phẩm");
                txID.setText("");
                txID.requestFocus();
                break;
            }
            else
            {
                flag4=1;
            }
        }
       if( flag==1&& flag2==1&& flag3==1 && flag4==1){
        int res=JOptionPane.showConfirmDialog(rootPane, "Bạn muốn thêm sản phẩm này ?");
        if(res==JOptionPane.YES_OPTION){ 
        if(bus.ThemSP(sp)){
         bus.dssp.add(sp);
         showResult();
        reset();
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        }
        }
       }
        else{
             JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
        }
        }
         else
             JOptionPane.showMessageDialog(rootPane, "Thêm thất bại");
       
    }//GEN-LAST:event_btnThemActionPerformed
   
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(kt()){
        SanPhamDTO sp1 = getfromTextfield();
        
        int i= tbl.getSelectedRow();
        if(i>=0){
            int res=JOptionPane.showConfirmDialog(rootPane, "Bạn muốn sửa sản phẩm này ?");
           if(res==JOptionPane.YES_OPTION){
            if(bus.SuaSP(sp1)){
                SanPhamDTO sp= bus.docdulieu().set(i, sp1);
                mode.setValueAt(sp1.getMaSP(), i, 0);
                mode.setValueAt(sp1.getTenSP(), i, 1);
                mode.setValueAt(sp.getGiaGoc(), i, 2);
                mode.setValueAt(sp1.getDonGia(), i, 3);
                mode.setValueAt(sp1. getSoLuong(), i, 4);
                mode.setValueAt(sp.getDonViTinh(), i, 5);
                mode.setValueAt(sp.getMaLoai(), i, 6);
                reset();
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
            }
           }
        }         
        }else
                JOptionPane.showMessageDialog(rootPane, "Sửa thất bại");
            
    }//GEN-LAST:event_btnSuaActionPerformed
   
    private void txThongtinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txThongtinKeyPressed

    }//GEN-LAST:event_txThongtinKeyPressed

    private void txThongtinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txThongtinKeyReleased
       if(cbTimKiem.getSelectedIndex()==0){
        showSearchID();
       }
       if(cbTimKiem.getSelectedIndex()==1){
        showSearchTen();
       }
    }//GEN-LAST:event_txThongtinKeyReleased

    private void cbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTimKiemActionPerformed
       if(cbTimKiem.getSelectedIndex()==0){
        showSearchID();
        btnTim.setEnabled(false);
       }
       if(cbTimKiem.getSelectedIndex()==1){
        showSearchTen();
         btnTim.setEnabled(false);
       }
    }//GEN-LAST:event_cbTimKiemActionPerformed

    private void txThongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txThongtinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txThongtinActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    public void showSearchID(){
        mode.setRowCount(0);
        for(SanPhamDTO sp: bus.timKiemID(txThongtin.getText().toLowerCase())){
            mode.addRow(new Object[]{
               sp.getMaSP(),sp.getTenSP(),sp.getGiaGoc(),sp.getDonGia(),sp.getSoLuong(),sp.getDonViTinh(),sp.getMaLoai()
           });
        }
    }
    public void showSearchTen(){
        
        mode.setRowCount(0);
        for(SanPhamDTO sp1: bus.timKiemten(txThongtin.getText())){
            mode.addRow(new Object[]{
               sp1.getMaSP(),sp1.getTenSP(),sp1.getGiaGoc(),sp1.getDonGia(),sp1.getSoLuong(),sp1.getDonViTinh(),sp1.getMaLoai()
           });
        }
    }

    public void showResult(){
        
        SanPhamDTO sp= bus.dssp.get(bus.dssp.size()-1);
         mode.addRow(new Object[]{
               sp.getMaSP(),sp.getTenSP(),sp.getGiaGoc(),sp.getDonGia(),sp.getSoLuong(),sp.getDonViTinh(),sp.getMaLoai()
           });
       
      tbl.setModel(mode);
    }
    
 
    public void reset(){
        txID.setText("");
        txTen.setText("");
        txGiaGoc.setText("");
        txDonGia.setText("");
        txSL.setText("");
        cbDVT.setSelectedIndex(0);
        cbMaLoai.setSelectedIndex(0);
        txID.setEnabled(true);
        cbMaLoai.setEnabled(true);
        btnTim.setEnabled(true);
    }
    
    public void loadComboBox(){
       Vector maloai= bus.loadComboBox();
       cbMaLoai.setModel(new DefaultComboBoxModel<>(maloai));
   }
      
    public boolean kt(){
        boolean check=true;
        if(txID.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm còn trống");
            check= false;
        }
        
        if(txID.getText().length()>10){
            JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm không quá 10 ký tự");
            check= false;
        }
        
        if(txTen.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Tên sản phẩm còn trống");
           check= false;
        }
        try {
            if(txGiaGoc.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Gía gốc sản phẩm còn trống");
           check= false;
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gía gốc phải là số");
          check= false;
        }
        try {
            if(txDonGia.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Đơn giá sản phẩm còn trống");
            check= false;
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Đơn giá phải là số");
           check= false;
        }
        try {
            if(txSL.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Số lượng sản phẩm còn trống");
            check= false;
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
           check= false;
        }
        
       return check;
    }
    
     
    public SanPhamDTO getfromTextfield(){
        SanPhamDTO sp= new SanPhamDTO();
        
        sp.setMaSP(txID.getText());
        sp.setTenSP(txTen.getText());
        sp.setGiaGoc(Float.parseFloat(txGiaGoc.getText()));
        sp.setDonGia(Float.parseFloat(txDonGia.getText()));
        sp.setSoLuong(Integer.parseInt(txSL.getText()));
        sp.setDonViTinh((String) cbDVT.getSelectedItem());
        sp.setMaLoai((String) cbMaLoai.getSelectedItem());
        return sp;
    }
    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPhamGUI dialog = new SanPhamGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbDVT;
    private javax.swing.JComboBox<String> cbMaLoai;
    private javax.swing.JComboBox<String> cbTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDVT;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbGiaGoc;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbSL;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbThongtin;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txDonGia;
    private javax.swing.JTextField txGiaGoc;
    public javax.swing.JTextField txID;
    private javax.swing.JTextField txSL;
    private javax.swing.JTextField txTen;
    private javax.swing.JTextField txThongtin;
    // End of variables declaration//GEN-END:variables
}
